version: "3.7"

services:
  user_repository:
    container_name: UserRepository
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 8080:80
    environment:
      - CHOKIDAR_USEPOLLING=true
